name: sonata
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudnn
  - gcc=13.2
  - gxx=13.2
  - ninja
  - scipy
  - numpy<=1.26.4  # Required by SONATA
  - psutil
  - timm
  - addict
  - matplotlib
  - open3d
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  # NOTE: pytorch-cuda is NOT used here on Jetson (uses native JetPack CUDA)
  - pip:
    # Torch-scatter from custom wheel for torch 2.5.0 + CUDA 12.6 (adjust if needed)
    - torch-scatter @ https://data.pyg.org/whl/torch-2.5.0%2Bcu126/torch_scatter-2.1.2-cp310-cp310-linux_aarch64.whl

    # Flash-attention (may require patching on ARM, optional)
    - git+https://github.com/Dao-AILab/flash-attention.git

    # spconv must be built manually (not installable via pip on Jetson)
    - -e ./libs/spconv  # optional, placeholder if you're symlinking local repo
